### PR TITLE
graphql-dotnet#2549 Added support for Extensions

### PR DESCRIPTION
**Pull request by HakuTheWolfSpirit**
# This pull-request requires a change in the graphql-dotnet library

[graphql-dotnet#2549](https://github.com/graphql-dotnet/graphql-dotnet/issues/2549)
[graphql-dotnet#2550](https://github.com/graphql-dotnet/graphql-dotnet/pull/2550) (requires updated graphql package)

### CODE REVIEW

**Review by SerenityTn — APPROVED** [review]

**Comment by tlil** [comment]
>This pull-request requires a change in the `graphql-dotnet` library

@Popeye4242  ^ - what's the state of this? :-)

**Comment by HakuTheWolfSpirit** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/issues/2549#issuecomment-844272207

The upstream PR will probably not be merged.

**Comment by tlil** [comment]
Okay, so fine with me closing this PR?

**Comment by HakuTheWolfSpirit** [comment]
Yeah.

**Comment by Shane32** [comment]
Keep an eye on the other PR because we may address it in the next major version of GraphQL.NET

**Comment by tlil** [comment]
> Keep an eye on the other PR because we may address it in the next major version of GraphQL.NET

Cool. Thanks, @Shane32. Can re-open this PR if/when that happens :-)

**Comment by sungam3r** [comment]
Hi guys, I had a long break from the OSS this summer, so PRs have accumulated a lot. I do not lose hope to review them in winter.

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/pull/2719

**Pull request closed without merging**
