### PR TITLE
Bump GraphQL.NET to latest 7.8

### PR DESCRIPTION
**Pull request by clangelov**
As Convention repo is not on par with the latest version of graphql-dotnet-* libs
it won't do any harm to update it.

Tests are passing
Sample apps are running

### CODE REVIEW

**Review by tlil — APPROVED** [review]

**Comment by tlil** [comment]
Thnx 👍

**Comment by clangelov** [comment]
@tlil any ideas when this change will be available on NuGet?

**Comment by tlil** [comment]
> @tlil any ideas when this change will be available on NuGet?

Will bump a release now – sorry for the delay, @clangelov !

**Comment by tlil** [comment]
- [Release notes: 7.5.0](https://github.com/graphql-dotnet/conventions/releases/tag/7.5.0)
 - [NuGet](https://www.nuget.org/packages/GraphQL.Conventions/#versions-body-tab)

cc @clangelov @vcup

**Pull request merged**
