### PR TITLE
Add Guid/DateTimeOffset as known types in TypeResolver

### PR DESCRIPTION
**Pull request by huysentruitw**

### CODE REVIEW

**Comment by tlil** [comment]
@huysentruitw Can you please add unit tests for these as well?

**Comment by huysentruitw** [comment]
--

**Comment by huysentruitw** [comment]
Can't build unit test projects because of a very strange issue. I already ran `dotnet restore` multiple times but I still get this:

image

Any ideas?

**Comment by tlil** [comment]
Sorry for the slow reply @huysentruitw - I've been out. I'll get back to you on this in the next couple of days. Not had time to look at it yet.

**Comment by tlil** [comment]
@huysentruitw I've merged in your two PRs for adding `Guid` and `DateTimeOffset`. A new package has been pushed to NuGet (v1.1.9). I will address the unit test setup in a separate PR (I'm developing this on a Mac you see :)). Again, sorry for taking so long...

**Pull request closed without merging**
