### PR TITLE
Upgrade graphql dotnet to 2.1.0

### PR DESCRIPTION
**Pull request by huysentruitw**
* Adapt for metadata change
* Adapt to newly introduced DateTimeGraphType and DateTimeOffsetGraphType (see https://github.com/graphql-dotnet/graphql-dotnet/pull/665)

The introduction of the new DateTime graph types is probably a breaking change, so we might consider bumping the major version.

### CODE REVIEW

**Review by Igorbek — APPROVED** [review]
This seems to me to have more sense comparing to #105
Just curious then how to choose in conventions which flavor of `DateTime`s to use? How can I annotate a field that it is a `Date` and not `DateTime`?

**Comment by huysentruitw** [comment]
@Igorbek well, since we don't have a `Date` object in C# we can't do it by 'convention'. 

Maybe an attribute `[DateOnly]` that you can put on a `DateTime` field? Or define our own `Date` type? I think this needs to be investigated separately.

**Comment by Igorbek** [comment]
Totally agree. That was just out of curiosity. It is definitely a separate issue.

**Comment by tlil** [comment]
Hi guys - thanks for this. Apologies for having been absent for a while. Will look at this either later today or tomorrow and get back to you :+1:

**Comment by huysentruitw** [comment]
pssst... 😉 😍

**Review by tlil — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
