### PR TITLE
Call FetchData after execution instead of before #17

### PR DESCRIPTION
**Pull request by huysentruitw**

### CODE REVIEW

**Comment by huysentruitw** [comment]
Any feedback on this one? ;)

**Comment by tlil** [comment]
Sorry, I completely missed this @huysentruitw. Let me get back to you later today – I was going to work on some updates and improvements this afternoon.

**Comment by tlil** [comment]
I've got some other pending changes - @huysentruitw, are you good with me pushing back merging this to I have the rest of it ready mid/end of next week?

**Comment by huysentruitw** [comment]
Sure, no problem. In the meantime I'll publish my version of a data loader implementation, based on the DataLoader library, but slightly improved and simplified.

**Comment by tlil** [comment]
Sounds good - thanks!

**Comment by tlil** [comment]
@huysentruitw did you have any more changes for this?

**Comment by huysentruitw** [comment]
No, this is all that needs to happen. FetchData just needs to be called after execution, otherwise it is called too early to make any dataloader implementation work.

**Comment by tlil** [comment]
Gotcha :+1: Merging and pushing a new release then :)

**Comment by tlil** [comment]
https://github.com/graphql-dotnet/conventions/releases/tag/v1.2.12 @huysentruitw

**Comment by huysentruitw** [comment]
Tommy, can you please revert this PR? It seems like your code was good before this change. In my previous tests, I used a simple dataloader implementation that doesn't seem to work for sub-field resolvers. Once I fixed this dataloader, v1.2.12 seems to hang because it now waits for all resolvers to complete, which doesn't happen before FetchData is called of course, this leads to a dead-lock situation (aka 🐔 🥚 problem).

With v1.2.11, everything seems to work as expected. 

Sorry for this inconvenience 😕

**Comment by tlil** [comment]
Reverted in v1.2.13 @huysentruitw  :)

**Pull request merged**
