### PR TITLE
Enhance enumerable graph type determing

### PR DESCRIPTION
**Pull request by vcup**
Hello,

I've noticed that IReadOnlyList<T> is not recognized as compatible with IEnumerable<T> in schema generation, which may limit the library's functionality in some scenarios.

This PR updates the IsEnumerableGraphType(TypeInfo) method in ReflectionExtensions.cs to use a simple check: `type.GetGenericTypeDefinition() == interfaceType.GetGenericTypeDefinition()`.
It will effect to GraphTypeInfo.cs#166 where marking the GraphTypeInfo.IsListType flag's logic.

Please consider merging this PR.

### CODE REVIEW

**Comment by vcup** [comment]
Hello @tlil , what are you thinks about this PR? have any advice?

**Comment by Shane32** [comment]
I'd like to comment that in the main GraphQL.NET package we had an issue where dictionaries and classes that implemented list interfaces were identified as collection types.  This was fixed in 5.1 in PR https://github.com/graphql-dotnet/graphql-dotnet/pull/3099 .  We restricted types that were identified as collection types to a set list, as follows:
- `IEnumerable`
- `IEnumerable<T>`
- `IList<T>`
- `List<T>`
- `ICollection<T>`
- `IReadOnlyCollection<T>`
- `IReadOnlyList<T>`
- `HashSet<T>`
- `ISet<T>`

Types that derived from these types would not be detected as a list.  While the old behavior was retained for a time with a global switch, it has since been removed.

Note that for auto-registering input types, GraphQL.NET must be able to reconstruct the list as well; to support more varied list types, we are adding `IListConverterFactory` for v8 - see https://github.com/graphql-dotnet/graphql-dotnet/pull/3931

Not sure how much of this applies here, but it seemed like it might be relevant, so I hope it helps.

**Comment by vcup** [comment]
I think we need recognize derived type as enumerable graph type, because most type are using from 3rd party packages and they will possible use class as Properties insteadof interface.
Maybe we can just avoid recognize the type where implemented `IDictionary` interface as it.

**Review by tlil — APPROVED** [review]
Sorry for the late response, @vcup. Thanks for putting this together. I've made some minor changes + added a test case for `IDictionary`. But otherwise, LGTM

**Comment by tlil** [comment]
> I'd like to comment that in the main GraphQL.NET package we had an issue where dictionaries and classes that implemented list interfaces were identified as collection types. (...) We restricted types that were identified as collection types to a set list, as follows:

Thanks for this added context, @Shane32. Will keep that in mind going forward if similar issues arise from this change.

**Pull request merged**
