### PR TITLE
Move FetchData callback to the BeforeExecutionStepAwaitedAsync overri…

### PR DESCRIPTION
**Pull request by huysentruitw**
…de to avoid dead-locking of the DataLoader

### CODE REVIEW

**Comment by huysentruitw** [comment]
See discussion at https://github.com/graphql-dotnet/graphql-dotnet/issues/855

**Review by tlil — APPROVED** [review]

**Comment by tlil** [comment]
Good spot - thanks for fixing. The step method didn't exist when this was first introduced.

**Comment by huysentruitw** [comment]
Nope, and we had to do all kinds of crazy stuff to keep the DataLoaders running, but with the step method the DataLoader implementation itself is much simpler. I stumbled upon this while creating the sample I wanted to PR 😄 

Thanks for your swift response!

**Comment by tlil** [comment]
Haha yep, I saw the other thread. Thanks for sorting :+1:

**Comment by huysentruitw** [comment]
@tlil any idea when this change will be released on NuGet? 😇

**Comment by tlil** [comment]
**Now**: https://ci.appveyor.com/project/tlil/conventions/builds/19525799 ;-)

Releases: https://github.com/graphql-dotnet/conventions/releases

**Pull request merged**
