### PR TITLE
Add support for IDataLoaderResult<>

### PR DESCRIPTION
**Pull request by kuzn-ilya**
Fix for #215

### CODE REVIEW

**Comment by Shane32** [comment]
Looks good to me, although I have never used this project.

**Comment by sungam3r** [comment]
I had a desire to try this project, but it never came to that. Also I think that after https://github.com/graphql-dotnet/graphql-dotnet/pull/1376 and some other refactoring the "main" project can approach the functionality of this project. I may be wrong.

**Comment by tlil** [comment]
> I had a desire to try this project, but it never came to that. Also I think that after [graphql-dotnet/graphql-dotnet#1376](https://github.com/graphql-dotnet/graphql-dotnet/pull/1376) and some other refactoring the "main" project can approach the functionality of this project. I may be wrong.

What are you getting at? What does that have to do with @kuzn-ilya's PR, @sungam3r ?

**Review by tlil — APPROVED** [review]

**Comment by sungam3r** [comment]
I just shared my thoughts. I am not familiar with this project. Do as you see fit.

**Pull request merged**
